import { build } from 'vite'
import { readFile, writeFile, rm } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
await build({ configFile: fileURLToPath(new URL('./vite.config.mjs', import.meta.url)) })
const html = await readFile(new URL('./.build/index.html', import.meta.url), 'utf8')
await writeFile(
  new URL('../src/components/rich-editor-bundle.ts', import.meta.url),
  '// Generated by pnpm editor:build. Do not edit.\nexport const editorHtml = ' +
    JSON.stringify(html) +
    '\n',
)
await rm(new URL('./.build', import.meta.url), { recursive: true })
