export {
  AUTH_ACCOUNT_MAX_LENGTH,
  AUTH_ACCOUNT_MIN_LENGTH,
  AUTH_ACCOUNT_PATTERN,
  AUTH_ERROR,
  AUTH_NICKNAME_MAX_LENGTH,
  AUTH_NICKNAME_MIN_LENGTH,
  AUTH_PASSWORD_MAX_LENGTH,
  AUTH_PASSWORD_MIN_LENGTH,
  authAgreementFooter,
  authCanSubmit,
  authSubmitLabel,
  authSwitchPrompt,
  extractAuthErrorMessage,
  isAccountReady,
  isNicknameValid,
  isPasswordReady,
  validateAuthSubmit,
  type AuthFormValues,
  type AuthMode,
} from './auth-form'
