import { build } from 'vite'
import { viteSingleFile } from 'vite-plugin-singlefile'
import { readFile, writeFile, rm } from 'node:fs/promises'
await build({
  root: import.meta.dirname,
  configFile: false,
  plugins: [viteSingleFile()],
  resolve: { dedupe: ['react', 'react-dom'] },
  build: { outDir: '.build', emptyOutDir: true, target: 'es2020', assetsInlineLimit: 10000000 },
})
const html = await readFile(new URL('./.build/index.html', import.meta.url), 'utf8')
await writeFile(
  new URL('./bundle.ts', import.meta.url),
  '// Generated by pnpm --filter @studycommit/puzzle-ui build:mobile.\nexport const puzzleHtml = ' +
    JSON.stringify(html) +
    '\n',
)
await rm(new URL('./.build', import.meta.url), { recursive: true })
