import { mistLightColors, radii, typography } from '@studycommit/design-tokens'

export const antdTheme = {
  token: {
    colorPrimary: '#4267A9',
    colorBgBase: mistLightColors.background,
    colorBgLayout: '#F3F5F8',
    colorBgContainer: mistLightColors.surface,
    colorBgElevated: mistLightColors.surface,
    colorText: mistLightColors.text,
    colorTextSecondary: mistLightColors.textMuted,
    colorTextDisabled: mistLightColors.textDisabled,
    colorBorder: mistLightColors.border,
    colorBorderSecondary: mistLightColors.border,
    colorSplit: mistLightColors.border,
    colorError: mistLightColors.danger,
    colorErrorBg: mistLightColors.dangerSurface,
    colorSuccess: mistLightColors.success,
    colorSuccessBg: mistLightColors.successSurface,
    colorWarning: mistLightColors.warning,
    colorWarningBg: mistLightColors.warningSurface,
    colorInfo: mistLightColors.primary,
    colorLink: mistLightColors.primary,
    borderRadius: radii.sm,
    borderRadiusLG: radii.md,
    fontSize: typography.bodySmall.fontSize,
    fontFamily: '-apple-system, BlinkMacSystemFont, "PingFang SC", "Microsoft YaHei", sans-serif',
    controlHeight: 36,
  },
  components: {
    Layout: {
      headerHeight: 64,
      siderBg: mistLightColors.surface,
      headerBg: mistLightColors.surface,
      bodyBg: mistLightColors.background,
    },
    Menu: {
      itemBg: mistLightColors.surface,
      itemSelectedBg: mistLightColors.primarySurface,
      itemSelectedColor: mistLightColors.onPrimarySurface,
      itemColor: mistLightColors.text,
      itemHoverBg: mistLightColors.surfaceMuted,
    },
    Table: {
      headerBg: mistLightColors.surfaceMuted,
      rowHoverBg: mistLightColors.surfaceMuted,
      cellPaddingBlock: 16,
      cellPaddingInline: 20,
    },
    Button: { fontWeight: 500, primaryShadow: 'none', defaultShadow: 'none' },
    Card: { headerFontSize: 16, headerHeight: 56 },
    Input: { paddingInline: 12, activeShadow: `0 0 0 3px ${mistLightColors.primarySurface}` },
    Select: { optionSelectedBg: mistLightColors.primarySurface },
    Tabs: { horizontalItemGutter: 28 },
  },
}
